### ISSUE TITLE
support for multiple sites

### ISSUE THREAD

**Issue by phish108** [phish108/authomator#2]
If we have two sites with different CNAMEs, then authomator works only for one of them. 

The service needs to register, which request URL has been posted. 

This needs a bit of adaptation for different sites. The only common element across sites are the ports of the services.

Our configuration may change to: 

```yaml
common: 
    frontend: 
        port: 8080
    checker:
        port: 8081
sites: 
  - common:
          base_url: "https://site1" // some host url for the baseline for all requests
          entrypoint: /auth/ // the entrypoint for the authomator
          success_target: "/home/" // where to point users after successfull authentication
    backend: 
          backendname:
              name: Display Name
              icon: FontAwesomeIcon
              type: github
              baseurl: https://github.com
              client_id: githubs client_id
              client_secret: githubs client_secret
    user:
       - login: username
         scope: internal user scope for acl
  - common: 
          base_url: "https://site2" // some host url for the baseline for all requests
          entrypoint: /auth/ // the entrypoint for the authomator
          success_target: "/success/" // where to point users after successfull authentication
    backend: 
          backendname:
              name: Display Name
              icon: FontAwesomeIcon
              type: github
              baseurl: https://github.enterprise.com
              client_id: githubs client_id
              client_secret: githubs client_secret
    user:
       - login: otherusername
         scope: internal user scope for acl
```
